name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 进入任务
        uses: actions/checkout@v3

      - name: 安装nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        
      - name: 安装依赖
        run: yarn install
        
      - name: 打包项目
        run: yarn run build

      - name: 项目部署
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_POR: '22'
          SOURCE: 'build/'
          TARGET: '/wwwroot/blog'
