name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 进入任务
        uses: actions/checkout@v3

      - name: 安装nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        
      - name: 安装依赖
        run: yarn install
        
      - name: 打包项目
        run: yarn run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://test/htdocs
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          local-dir: ./build/
          server-dir: ./htdocs/
        env:
          CI: true
